export const balancedQuestions = [
  {
    sequence: 1,
    type: "MULTIPLE_CHOICE",
    statement: "Quando você se depara com um problema complexo no trabalho ou estudos, qual costuma ser sua primeira atitude?",
    options: [
      { id: "A", label: "Quebro o problema em partes lógicas e começo a construir uma solução passo a passo.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Analiso os dados e o histórico disponível para encontrar tendências ou anomalias.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Procuro entender como isso afeta a experiência da pessoa que está usando o sistema.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Verifico a estabilidade do ambiente e se os recursos de rede/servidor estão operacionais.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Investigo pontos fracos, brechas de segurança ou riscos de falha crítica no processo.", targetArea: "Cibersegurança" },
      { id: "F", label: "Alinho com as pessoas envolvidas para entender prioridades e organizar a entrega.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 2,
    type: "MULTIPLE_CHOICE",
    statement: "Que tipo de atividade no dia a dia traz mais satisfação para você?",
    options: [
      { id: "A", label: "Escrever código ou criar automações funcionais que resolvem uma tarefa.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Extrair conclusões valiosas a partir de grandes volumes de informações.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Desenhar interfaces intuitivas e tornar jornadas de uso simples e agradáveis.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Configurar ambientes, servidores e garantir alta disponibilidade sem interrupções.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Proteger sistemas contra acessos indevidos e mitigar vulnerabilidades.", targetArea: "Cibersegurança" },
      { id: "F", label: "Definir a visão de um produto, priorizar recursos e alinhar a equipe ao negócio.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 3,
    type: "MULTIPLE_CHOICE",
    statement: "Ao analisar um aplicativo ou sistema famoso, o que costuma chamar mais sua atenção?",
    options: [
      { id: "A", label: "As funcionalidades, a velocidade de execução e a lógica do sistema.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Como ele utiliza dados para personalizar recomendações e prever comportamentos.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "O visual, a facilidade de navegação e o conforto estético e funcional da interface.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "A capacidade do sistema suportar milhões de acessos simultâneos sem cair.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Os métodos de autenticação, privacidade de dados e mecanismos antifraude.", targetArea: "Cibersegurança" },
      { id: "F", label: "A estratégia de mercado do produto, suas funcionalidades-chave e proposta de valor.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 4,
    type: "MULTIPLE_CHOICE",
    statement: "Qual dessas tarefas você escolheria realizar em um projeto de tecnologia?",
    options: [
      { id: "A", label: "Desenvolver APIs, bancos de dados ou regras de negócio do sistema.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Criar modelos preditivos, dashboards analíticos ou fluxos de dados.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Entrevistar usuários reais e desenhar protótipos de telas para testes.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Orquestrar contêineres, redes virtuais e pipelines de implantação em nuvem.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Realizar testes de invasão e aplicar regras de conformidade e segurança.", targetArea: "Cibersegurança" },
      { id: "F", label: "Mapear requisitos, negociar prazos e organizar o roadmap do time de desenvolvimento.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 5,
    type: "MULTIPLE_CHOICE",
    statement: "Pensando no seu impacto ideal em uma empresa, você prefere ser reconhecido por:",
    options: [
      { id: "A", label: "Entregar recursos funcionais e códigos limpos e bem estruturados.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Gerar insights estratégicos baseados em dados que orientam decisões da empresa.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Criar produtos que os clientes amam usar pela facilidade e clareza.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Garantir alta disponibilidade na infraestrutura e tempos de resposta rápidos.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Manter a empresa protegida contra vazamentos de dados e ataques cibernéticos.", targetArea: "Cibersegurança" },
      { id: "F", label: "Liderar a estratégia do produto e garantir entregas alinhadas aos objetivos de negócio.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 6,
    type: "MULTIPLE_CHOICE",
    statement: "Ao trabalhar em equipe para lançar uma nova funcionalidade, qual seria o seu papel ideal?",
    options: [
      { id: "A", label: "Garantir que a lógica e o código funcionem sem erros.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Medir o impacto da funcionalidade usando métricas e estatísticas.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Assegurar que a funcionalidade seja acessível e fácil de entender.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Preparar os servidores para aguentar o aumento de tráfego esperado.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Revisar as permissões e checar se não introduzimos falhas de segurança.", targetArea: "Cibersegurança" },
      { id: "F", label: "Gerenciar as expectativas, prazos e os critérios de sucesso da entrega.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 7,
    type: "MULTIPLE_CHOICE",
    statement: "O que te deixa mais frustrado ao usar um produto digital?",
    options: [
      { id: "A", label: "Bugs, travamentos constantes e lentidão no processamento.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Recomendações que não fazem sentido e informações imprecisas.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Layout confuso, botões escondidos e textos difíceis de ler.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "O sistema ficar fora do ar por muito tempo ou apresentar erro 500.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Falta de transparência sobre o uso dos meus dados e invasões frequentes.", targetArea: "Cibersegurança" },
      { id: "F", label: "Funcionalidades inúteis que não resolvem meu problema real.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 8,
    type: "MULTIPLE_CHOICE",
    statement: "Se você tivesse que ler um livro ou fazer um curso agora, sobre qual tema seria?",
    options: [
      { id: "A", label: "Padrões de arquitetura de sistemas e novas linguagens de programação.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Estatística aplicada, Machine Learning e visualização de informações.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Psicologia cognitiva aplicada a interfaces e comportamento do usuário.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Automação de processos operacionais, Cloud Computing e DevOps.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Criptografia, hacking ético e políticas de proteção de rede.", targetArea: "Cibersegurança" },
      { id: "F", label: "Modelos de negócio, metodologias ágeis e inovação corporativa.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 9,
    type: "MULTIPLE_CHOICE",
    statement: "Como você prefere lidar com desafios inesperados de última hora?",
    options: [
      { id: "A", label: "Encontrando soluções criativas através de código ou reestruturação lógica.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Consultando relatórios ou métricas rápidas para embasar minha decisão.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Realinhando o design ou os fluxos para não prejudicar a jornada do usuário.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Alocando mais recursos de forma rápida para conter quedas ou falhas físicas.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Aplicando correções ou bloqueios imediatos para evitar que o dano se espalhe.", targetArea: "Cibersegurança" },
      { id: "F", label: "Redefinindo o escopo, comunicando as partes interessadas e renegociando o plano.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
  {
    sequence: 10,
    type: "MULTIPLE_CHOICE",
    statement: "Qual é a sua visão sobre o futuro da tecnologia?",
    options: [
      { id: "A", label: "Sistemas cada vez mais inteligentes, eficientes e integrados por código.", targetArea: "Desenvolvimento de Software" },
      { id: "B", label: "Decisões totalmente baseadas em análise preditiva e inteligência artificial.", targetArea: "Dados e Inteligência Artificial" },
      { id: "C", label: "Interfaces invisíveis, hiper-personalizadas e mais humanas.", targetArea: "Design e Experiência do Usuário" },
      { id: "D", label: "Computação em nuvem onipresente, escalável e extremamente rápida.", targetArea: "Infraestrutura e Redes" },
      { id: "E", label: "Uma batalha constante por privacidade, identidade digital e proteção contra ameaças.", targetArea: "Cibersegurança" },
      { id: "F", label: "Produtos mais enxutos, focados na resolução de problemas específicos com maior valor.", targetArea: "Gestão de Produtos de Tecnologia" },
    ],
  },
] as const;
